language: go

go:
  - 1.7
  - tip

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install: true

script:
  - go install
  - go test -v -covermode=count -coverprofile=profile.cov github.com/ovh/svfs/svfs
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=svfs
