language: go

go:
  - 1.7
  - tip

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install: true

script:
  - go install
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      for pkg in $(go list github.com/ovh/svfs/... | grep -v vendor); do
        go test -v -covermode=count -coverprofile=cover.$(date +%s) $pkg;
      done;

      echo "mode: set" > profile.cov;
      cat cover.* | grep -v "mode:" | sort -r | awk '{if($1 != last) {print $0;last=$1}}' >> profile.cov;
      rm -f cover.*;
    fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=svfs; fi'
